const defiKnowledgeBase = {
  "defi": "DeFi, or Decentralized Finance, refers to a system of financial services and applications built on blockchain technology. It aims to recreate traditional financial systems (like lending, borrowing, trading) without centralized intermediaries such as banks. DeFi uses smart contracts to execute financial transactions and agreements automatically.",

  "defi basics": "DeFi basics include understanding key concepts such as:\n1. Blockchain technology\n2. Smart contracts\n3. Decentralized applications (DApps)\n4. Cryptocurrencies and tokens\n5. Decentralized exchanges (DEXs)\n6. Lending and borrowing platforms\n7. Yield farming and liquidity mining\n8. Governance tokens and DAOs (Decentralized Autonomous Organizations)\nThese components form the foundation of the DeFi ecosystem.",

  "what is defi": "DeFi, or Decentralized Finance, refers to a system of financial services and applications built on blockchain technology. It aims to recreate traditional financial systems (like lending, borrowing, trading) without centralized intermediaries such as banks. DeFi uses smart contracts to execute financial transactions and agreements automatically.",

  "what are the main risks in defi": "The main risks in DeFi include:\n1. Smart contract vulnerabilities: Bugs in code can lead to hacks or unexpected behavior.\n2. Liquidity risks: Lack of liquidity can lead to slippage or inability to exit positions.\n3. Market volatility: Crypto markets are highly volatile, leading to potential rapid value loss.\n4. Regulatory uncertainty: Unclear regulations could impact DeFi operations and legality.\n5. Oracle manipulation: Incorrect price feeds can be exploited.\n6. Impermanent loss: Risk for liquidity providers when asset prices change.\n7. Governance attacks: Malicious actors could manipulate protocol governance.\n8. Scalability issues: Network congestion can lead to high fees and slow transactions.",

  "how can i assess protocol risk": "To assess protocol risk:\n1. Audit history: Check for reputable third-party audits.\n2. TVL (Total Value Locked): Higher TVL often indicates more trust, but also a bigger target.\n3. Team reputation: Research the team's background and track record.\n4. Code transparency: Verify if the code is open-source and well-documented.\n5. Community engagement: Active communities can indicate a healthy protocol.\n6. Longevity: Protocols that have survived longer may be more reliable.\n7. Insurance coverage: Check if the protocol is covered by DeFi insurance platforms.\n8. Governance structure: Understand how protocol changes are made.\n9. Dependencies: Assess risks of integrated protocols or oracles.",

  "what is impermanent loss": "Impermanent loss occurs in liquidity pools when the price ratio of paired assets changes compared to when they were deposited. It represents the difference between holding assets in a liquidity pool versus holding them separately. The loss is 'impermanent' because it can be recovered if prices return to their original ratio. Factors affecting impermanent loss include:\n1. Price volatility of paired assets\n2. The extent of the price change\n3. The time assets spend in the pool\nStrategies to mitigate impermanent loss include choosing stable pairs or using concentrated liquidity positions.",

  "how does yield farming work": "Yield farming involves strategically lending or staking crypto assets to generate returns. The process typically involves:\n1. Depositing assets into a DeFi protocol (e.g., lending platform, liquidity pool)\n2. Earning rewards in the form of interest, trading fees, or additional tokens\n3. Often, reinvesting rewards to compound returns\n4. Sometimes, leveraging positions to increase potential yields\nYield farmers often move assets between different protocols to maximize returns. Risks include smart contract vulnerabilities, impermanent loss, and high gas fees. Popular yield farming strategies include liquidity provision, lending, and staking in governance protocols.",

  "what is a smart contract": "A smart contract is a self-executing contract with the terms of the agreement directly written into code. It runs on a blockchain network and automatically executes when predetermined conditions are met. Key features include:\n1. Automation: Executes without intermediaries\n2. Transparency: Visible to all network participants\n3. Immutability: Cannot be altered once deployed\n4. Efficiency: Reduces the need for intermediaries\nSmart contracts are fundamental to DeFi, enabling complex financial operations without traditional intermediaries. However, they can be vulnerable to bugs and exploits if not properly audited and tested.",

  "what is total value locked (tvl)": "Total Value Locked (TVL) is a metric used in DeFi to measure the overall value of crypto assets deposited in a protocol. It represents the sum of all assets staked, locked, or deposited in various DeFi services like lending platforms, liquidity pools, or yield farming protocols. TVL is important because it:\n1. Indicates the size and adoption of a DeFi protocol\n2. Can be used to compare different protocols\n3. Often correlates with the protocol's security and liquidity\nHowever, high TVL also means a protocol might be a more attractive target for hackers.",

  "what are decentralized exchanges (dex)": "Decentralized Exchanges (DEXs) are cryptocurrency exchanges that operate without a central authority. Key features include:\n1. Non-custodial: Users retain control of their funds\n2. Permissionless: Anyone can use them without KYC\n3. Automated: Use smart contracts for trades\n4. Liquidity pools: Often rely on user-provided liquidity\nPopular DEXs include Uniswap, SushiSwap, and PancakeSwap. Advantages include reduced counterparty risk and increased privacy. Disadvantages can include lower liquidity for some pairs and potential for front-running attacks.",

  "what is liquidity mining": "Liquidity mining is a process where users provide liquidity to a protocol and receive rewards in return, typically in the form of the protocol's native token. It's a way for protocols to bootstrap liquidity and distribute tokens. The process usually involves:\n1. Depositing assets into a liquidity pool\n2. Receiving LP (Liquidity Provider) tokens\n3. Staking these LP tokens to earn additional rewards\nLiquidity mining was popularized by Compound in 2020 and played a significant role in the 'DeFi summer'. While it can offer high yields, risks include impermanent loss and potential for 'rug pulls' in less reputable projects.",

  "what are flash loans": "Flash loans are uncollateralized loans in DeFi that must be borrowed and repaid within a single blockchain transaction. Key points:\n1. No collateral required\n2. Must be repaid in the same transaction\n3. If not repaid, the transaction is reversed\n4. Often used for arbitrage or collateral swaps\nWhile flash loans enable capital-efficient operations, they've also been used in several high-profile DeFi exploits. They require deep understanding of DeFi protocols and smart contract interactions to use effectively and safely."
};

export function getDefiAnswer(question: string): string {
  const lowerCaseQuestion = question.toLowerCase();
  for (const [key, value] of Object.entries(defiKnowledgeBase)) {
    if (lowerCaseQuestion.includes(key) || key.includes(lowerCaseQuestion)) {
      return value;
    }
  }
  return "I'm sorry, I don't have specific information about that. Please ask another DeFi-related question.";
}